import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/useEffectOne" className={styles.one}>useEffectOne</Link>
        <Link href="/useEffectTwo" className={styles.two}>useEffectTwo</Link>
        <Link href="/useEffectThree" className={styles.three}>useEffectThree</Link>
        <Link href="/carouselPage" className={styles.carousel}>Carousel Page</Link>
      </main>
    </>
  )
}
